services:
  - type: web
    name: ultravox-twilio-caller
    env: node
    region: oregon
    plan: starter
    buildCommand: npm ci
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: ULTRAVOX_API_KEY
        sync: false
      - key: GHL_API_KEY
        sync: false  
      - key: GHL_LOCATION_ID
        sync: false
      - key: PORT
        value: 10000
      - key: SERVER_BASE_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: data
      mountPath: /tmp
      sizeGB: 1
